name: Test Firmware on PR

on:
  pull_request:
    branches:
      - main
    paths:
      - 'main/**'
      - 'src/**'
      - 'tests/**'
      - 'CMakeLists.txt'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcjson-dev build-essential

    - name: Run unit tests
      run: |
        cd tests
        make clean
        make test

  firmware-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build ESP32 firmware
      uses: espressif/esp-idf-ci-action@v1.2.0
      with:
        esp_idf_version: 'release-v5.1'
        command: |
          idf.py build

    - name: Check code quality
      uses: espressif/esp-idf-ci-action@v1.2.0
      with:
        esp_idf_version: 'release-v5.1'
        command: |
          echo "Checking for basic code quality issues..."
          
          # Check for common issues in main.c
          if grep -n "malloc(" main/main.c | grep -v "free("; then
            echo "Warning: Found malloc calls, ensure corresponding free() calls exist"
          fi
          
          # Check for potential buffer overflows
          if grep -n "strcpy\|strcat\|sprintf" main/main.c; then
            echo "Warning: Found potentially unsafe string functions. Consider using safe alternatives."
          fi
          
          echo "Code quality check completed."
