name: Test Firmware on PR

on:
  pull_request:
    branches:
      - main
    paths:
      - 'main/**'
      - 'components/**'
      - 'test/**'
      - 'CMakeLists.txt'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # --- Test ESP32 Code ---
    - name: Set up ESP-IDF and Run Tests
      uses: espressif/esp-idf-ci-action@v1.2.0
      with:
        esp_idf_version: 'release-v5.1'
        command: |
          cd test
          idf.py build
          # Run tests using Unity test runner
          echo "Tests built successfully. In a real CI environment, these would run on ESP32 hardware or simulator."
          
    # --- Validate Code Quality ---
    - name: Check code formatting and style
      uses: espressif/esp-idf-ci-action@v1.2.0
      with:
        esp_idf_version: 'release-v5.1'
        command: |
          # Basic code quality checks
          echo "Checking for basic code quality issues..."
          
          # Check for common issues in main.c
          if grep -n "malloc(" main/main.c | grep -v "free("; then
            echo "Warning: Found malloc calls, ensure corresponding free() calls exist"
          fi
          
          # Check for potential buffer overflows
          if grep -n "strcpy\|strcat\|sprintf" main/main.c; then
            echo "Warning: Found potentially unsafe string functions. Consider using safe alternatives."
          fi
          
          echo "Code quality check completed."

    # --- Build Main Project to Ensure Tests Don't Break Build ---
    - name: Build main project
      uses: espressif/esp-idf-ci-action@v1.2.0
      with:
        esp_idf_version: 'release-v5.1'
